Test pre-commit

diff --git a/.git-hooks/pre-commit b/.git-hooks/pre-commit
--- a/.git-hooks/pre-commit
+++ b/.git-hooks/pre-commit
@@ -1,8 +1,17 @@
 #!/bin/bash
 
-# Lint Check
-echo 'olar'
+has_changed() {
+    # Work out what to diff against, really HEAD will work for any established repository.
+    if git rev-parse --verify HEAD >/dev/null 2>&1; then
+        against=HEAD
+    else
+        # Initial commit: diff against an empty tree object
+        against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+    fi
 
-# PSR1 & PSR2 syntax check
-
-# EditorConfig syntax check
+    diffstr=`git diff --cached $against`
+    if [[ -n "$diffstr" ]] ; then
+        echo "You have left DONOCOMMIT in your changes, you can't commit until it has been removed."
+        exit 1
+    fi
+}
